import json
import re

JSON_PATH = "/Users/gowthamjadapalli/Documents/GitHub/leaderledger/src/data/candidates.json"

overrides = {
    4: "completed Master of Science from Osmania University in 2006",
    9: "completed 10th Class (SSC) from ZP High School, Budithi",
    12: "completed B.E. (Civil) from Gulbharga University in 1990",
    16: "completed Bachelor of Engineering (Civil) from Bangalore University in 1998",
    19: "completed Intermediate from Govt Jr College, Srungavarapukota in 1987",
    21: "completed M.A. from Andhra University in 2008",
    22: "completed Bachelor of Commerce from A.M.A.L College, Anakapalli in 1978",
    24: "completed Bachelor of Education from Andhra University in 2015",
    25: "completed B.A. and B.L. from Andhra University in 1992",
    27: "completed M.Com from A.M.A.L College, Anakapalle",
    28: "completed M.Com from A.M.A.L College, Anakapalle",
    29: "completed Intermediate from Board of Intermediate Education, AP in 1975",
    30: "completed B.Sc. (Ag) from Gorakhpur University in 1981",
    31: "completed Bachelor of Commerce from Mrs. A.V.N. College, Andhra University in 1990",
    34: "completed B.Sc. from Mrs. A.V.N College, Visakhapatnam in 1988",
    35: "completed M.A. from Andhra University in 2009",
    36: "completed Master of Business Administration from Osmania University in 2006",
    38: "completed M.B.A. from Andhra University in 2006",
    39: "completed 9th Class from ZP High School, Yeleswaram in 1965",
    40: "completed 9th Class from ZP High School, Yeleswaram in 1965",
    42: "completed Master of Computer Applications (M.C.A) from Osmania University in 2003",
    43: "completed M.Sc (Information Systems) from Sri GCSR College, Rajam in 2003",
    44: "completed Bachelor of Arts (B.A) from SKBR College, Amalapuram in 1978",
    45: "completed Master of Social Work from Nagarjuna University in 2008",
    46: "completed Bachelor of Arts (B.A) from SKBR College, Amalapuram in 1978",
    48: "completed B.E. from Madras University in 2003",
    49: "completed B.E. from Madras University in 2003",
    51: "completed Bachelor of Commerce from SGS College, Andhra University in 1984",
    52: "completed B.Sc. from Government Arts and Science College, Rajahmundry in 1967",
    53: "completed B.E. from Madras University in 2003",
    54: "completed B.Com from VKV Govt. Degree College, Kothapeta in 1984",
    55: "completed 10th Class (SSC) from Sri Patibandla Sitaramaiah High School in 1985",
    56: "completed 10th Class (SSC) from Sri Patibandla Sitaramaiah High School in 1985",
    57: "completed Intermediate from D.R. Goenka Govt. Degree College, Pentapadu in 1976",
    58: "completed Intermediate from D.R. Goenka Govt. Degree College, Pentapadu in 1976",
    62: "completed B.Tech from CR Reddy College, Eluru in 2002",
    63: "completed B.Tech from CR Reddy College, Eluru in 2002",
    64: "completed B.Sc. from Hindu College, Nagarjuna University in 1997",
    65: "completed M.Sc in Computers from Nagarjuna University in 1997",
    66: "completed B.A. from DNR College, Bhimavaram in 1994",
    67: "completed Intermediate from SKBR Govt. College, Macherla in 1982",
    68: "completed B.Sc. from AG & SG College, Vuyyuru, Nagarjuna University in 1998",
    69: "completed B.A. from DNR College, Bhimavaram, Andhra University in 1987",
    70: "completed M.B.B.S. from Rangaraya Medical College, Kakinada in 1972",
    72: "completed B.Pharmacy from Andhra University in 1984",
    74: "completed Intermediate from Hindu College, Machilipatnam in 1970",
    75: "completed M.A. from Andhra University PG College, Kakinada in 1993",
    77: "completed Ph.D in Geography from Andhra University in 2005",
    79: "completed B.Tech from RVR & JC Engineering College, Guntur in 1992",
    80: "completed Master of Engineering from PSG College of Technology in 1986",
    81: "completed M.Sc. (Botany) from Andhra University in 1981",
    82: "completed M.Sc. (Botany) from Andhra University in 1981",
    83: "completed 10th Class (SSC) from ZPH School, Penamaluru in 1983",
    84: "completed M.Sc. Microbiology from Dharwar University in 1978",
    85: "completed M.Sc. Microbiology from Dharwar University in 1978",
    86: "completed B.Com from TJPS College, Guntur in 1976",
    87: "completed 10th Class (SSC) from Ravindra Bharathi School, Bhimavaram in 1989",
    88: "completed 10th Class (SSC) from ZP High School, Munjuluru in 1972",
    89: "completed B.Sc. from JKC College, Guntur",
    91: "completed B.Tech from Mysore University in 1989",
    92: "completed Master of Business Administration from Osmania University in 1987",
    95: "completed B.E. (Civil) from Muffakham Jah College of Engineering in 1997",
    96: "completed Ph.D from Sri Krishnadevaraya University in 2019",
    98: "completed B.A. from Andhra University in 2002",
    99: "completed Bachelor of Laws from Andhra University in 1995",
    100: "completed B.A. from New Government College, Hyderabad in 1977",
    101: "completed B.A. from Osmania College, Kurnool",
    104: "completed B.Sc. from Anwar Ul-Ulam Autonomous College, Hyderabad in 1990",
    106: "completed 10th Class (SSC) from Govt. Junior College, Pittalavanipalem in 1985",
    107: "completed 10th Class from National Institute of Open School in 2010",
    108: "completed M.B.B.S. from Sri Ramachandra Medical College, Chennai",
    109: "completed M.B.B.S. from Deccan College of Medical Science, Hyderabad in 2004",
    110: "completed B.Com from Distance Education",
    111: "completed Master of Legislative Laws from Sri Krishna Devaraya University in 2018",
    112: "completed Master of Business Administration from Cardiff University",
    113: "completed B.A. from Government Degree College, Nandikotkur in 1990",
    114: "completed Bachelor of Engineering (Discontinued) from Gulbarga University",
    115: "completed Master of Dental Surgery from Government Dental College, Hyderabad in 2005",
    116: "completed Intermediate from Sri Vivekananda Junior College, Giddalur in 1985",
    119: "completed Master of Business Administration from Institute of Computer and Business Management, Hyderabad in 2001",
    122: "completed B.Tech from P.E.S. Institute of Technology, Bangalore in 1998",
    123: "completed Matriculation from Municipal High School, Nandyal",
    124: "completed M.B.B.S. from JJM Medical College, Dhavanagere in 2000",
    126: "completed BBM from IIP College, Hyderabad in 2009",
    129: "completed M.B.B.S. from Kurnool Medical College in 1999",
    130: "completed Post Graduate Diploma from T.A.PAI Management Institute, Manipal in 1987",
    132: "completed M.A. from Sri Krishnadevaraya University in 1994",
    135: "completed 10th Class (SSC) from Z.P. High School, Palugurallapalle in 1978",
    137: "completed 10th Class (SSLC) from Annebisent Municipal High School, Proddatur in 1959",
    138: "completed Masters in Mass Communications from St Francis College for Women in 2013",
    139: "completed Bachelor of Laws from Andhra University in 1975",
    141: "completed 8th Standard from Government High School, Dharmavaram in 1983",
    143: "completed 10th Class (SSC) from Board of Secondary Education AP in 1983",
    144: "completed Master of Business Administration from ITM, Chennai in 2013",
    145: "completed M.Sc in Information Technology from Middle Sex University, UK in 2005",
    146: "completed B.Com from V.R. College, Nellore in 1984",
    147: "completed Intermediate from K.A.C Junior College, Nellore in 1974",
    150: "completed Ph.D from Sri Venkateswara University in 2002",
    151: "completed Intermediate from Government Junior College in 1979",
    152: "completed B.A. from V.R College, Nellore in 1999",
    154: "completed B.Tech from Rajiv Gandhi Memorial College of Engineering, Nandyal",
    155: "completed Intermediate from Government Junior College, Kadiri in 1983",
    156: "completed Intermediate from Rayalaseema Junior College, Tirupathi in 1998",
    157: "completed B.A. from S.K. University, Anantapur in 1998",
    158: "completed B.A. from Nagarjuna University in 2020",
    159: "completed Ph.D in Adult Education from Sri Venkateswara University in 2021",
    160: "completed M.B.B.S. from Narayana Medical College in 2022",
    161: "completed 10th Class from Z.P. High School, Sodam",
    162: "completed B.A. from Nizam College, Osmania University in 1982",
    163: "completed B.A. from Nizam College, Osmania University in 1990",
    164: "completed Master of Business Administration from Bharath Institute, Chennai in 2005",
    165: "completed 10th Class (SSC) from Loyola Boarding School, Vinnukonda in 1987",
    166: "completed B.A. from S.V. Arts College, Tirupati in 1975",
    167: "completed B.A. (Discontinued) from PVKN Govt. Degree College, Chittoor",
    169: "completed 10th Class (SSC) from Arogyavaram English Medium High School in 1985",
    170: "completed 10th Class (SSC) from Hyderabad Public School",
    171: "completed Ph.D in Commerce from Sri Venkateswara University in 2013",
    173: "completed B.Com from V.V. Puram College, Bangalore University in 1980"
}

with open(JSON_PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)

for cand in data:
    cid = cand.get('id')
    if cid in overrides:
        cand['education'] = overrides[cid]

with open(JSON_PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

print("✨ Cleanup logic 3 complete!")
